Section "ServerLayout"
    Identifier "Layout"
    Screen 0 "Screen"
EndSection

Section "Device"
    Identifier "DummyVideo"
    Driver "dummy"
    VideoRam 256000
EndSection

Section "Monitor"
    Identifier "Monitor"
    HorizSync 28.0-80.0
    VertRefresh 48.0-75.0
    Modeline "960x540" 40.75 960 1008 1104 1248 540 543 553 566
EndSection

Section "Screen"
    Identifier "Screen"
    Device "DummyVideo"
    Monitor "Monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "960x540"
    EndSubSection
EndSection
