package eu.pb4.polymer.core.api.block;

import eu.pb4.polymer.core.api.utils.PolymerUtils;
import net.minecraft.class_2246;
import net.minecraft.class_2338;
import net.minecraft.class_2487;
import net.minecraft.class_2509;
import net.minecraft.class_2591;
import net.minecraft.class_2596;
import net.minecraft.class_2680;
import net.minecraft.class_9296;
import xyz.nucleoid.packettweaker.PacketContext;

public interface PolymerHeadBlock extends PolymerBlock {
    /**
     * This method is used to determine texture/skin of client sided head
     * Player Skin can be generated by https://mineskin.org/
     *
     * @param state Server-side BlockState
     * @param pos
     * @param context
     * @return Skin Value
     */
    String getPolymerSkinValue(class_2680 state, class_2338 pos, PacketContext context);
    default String getPolymerSkinSignature(class_2680 state, class_2338 pos, PacketContext context) {
        return null;
    };

    @Override
    default class_2680 getPolymerBlockState(class_2680 state, PacketContext context) {
        return class_2246.field_10432.method_9564();
    }

    /**
     * Creates client-side skull BlockEntity
     *
     * @param state Server-side BlockState
     * @param pos Block's position
     * @return A Packet
     */
    default class_2596<?> getPolymerHeadPacket(class_2680 state, class_2338 pos, PacketContext context) {
        class_2487 main = new class_2487();
        main.method_10582("id", "minecraft:skull");
        main.method_10566("profile", class_9296.field_49359.encodeStart(class_2509.field_11560,
                PolymerUtils.createProfileComponent(getPolymerSkinValue(state, pos, context),
                        getPolymerSkinSignature(state, pos, context))).result().get());
        main.method_10569("x", pos.method_10263());
        main.method_10569("y", pos.method_10264());
        main.method_10569("z", pos.method_10260());
        return PolymerBlockUtils.createBlockEntityPacket(pos, class_2591.field_11913, main);
    }

    @Override
    default void onPolymerBlockSend(class_2680 blockState, class_2338.class_2339 pos, PacketContext.NotNullWithPlayer context) {
        context.getPlayer().field_13987.method_14364(this.getPolymerHeadPacket(blockState, pos.method_10062(), context));
    }
}
